# Generated by Django 2.2.6 on 2019-10-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wall Outlet', max_length=200, unique=True)),
                ('connector_image', models.ImageField(blank=True, null=True, upload_to='connectors')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200, unique=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(blank=True, default='', max_length=55)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(max_length=55)),
                ('landmark', models.CharField(blank=True, default='', max_length=55)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, default='', max_length=1000)),
                ('amenities', models.CharField(blank=True, default='', max_length=255)),
                ('station_type', models.CharField(choices=[('HOME', 'Home'), ('COMMERCIAL', 'Commercial'), ('UNKNOWN', 'unknown'), ('SHOPPING_MALL', 'SHOPPING_MALL')], default='UNKNOWN', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='unique code of each point')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('status', models.CharField(choices=[('WORKING', 'WORKING'), ('COMING_SOON', 'COMING_SOON'), ('IN_REPAIR', 'In Repair/Not Funtioning'), ('REMOVED', 'REMOVED')], default='WORKING', max_length=55)),
                ('cost_per_hr', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('compatibility', models.CharField(blank=True, default='ALL', max_length=255, verbose_name='vehicle name')),
                ('notes', models.CharField(max_length=255)),
                ('power_output', models.FloatField(verbose_name='in kW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.ConnectorType')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.Station')),
            ],
        ),
    ]
