# Generated by Django 2.2.6 on 2019-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Contact person name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address of station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Extra details(optional)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number of person'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name Of charging station'),
        ),
    ]
